# Generated by Django 4.0.2 on 2022-06-24 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fullname',
            field=models.CharField(blank=True, max_length=50, verbose_name='Fullname'),
        ),
    ]
