# Generated by Django 4.0.2 on 2022-03-05 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_profile_current_contest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['username']},
        ),
    ]
