# Generated by Django 4.0.2 on 2022-03-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_profile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.FileField(blank=True, max_length=150, upload_to='uploads/', verbose_name='Logo override image'),
        ),
    ]
