# Generated by Django 4.0.2 on 2022-03-05 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
            ],
            options={
                'verbose_name': 'problem level',
                'verbose_name_plural': 'problem levels',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ['code'], 'permissions': (('view_private_problem', 'View private Math problems'), ('edit_own_problem', 'Edit own Math problems'), ('edit_all_problem', 'Edit all Math problems'), ('edit_public_problem', 'Edit all public Math problems'), ('see_organization_problem', 'See organizations-private Math problems'), ('change_public_visibility', 'Change public math problem visibility')), 'verbose_name': 'Problem', 'verbose_name_plural': 'Problems'},
        ),
        migrations.AddField(
            model_name='problem',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='education.level', verbose_name='level'),
        ),
    ]
