# Generated by Django 4.0.2 on 2022-03-05 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_level_alter_problem_options_problem_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='level',
        ),
        migrations.DeleteModel(
            name='Level',
        ),
    ]
