# Generated by Django 4.0.2 on 2022-06-13 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('education', '0002_remove_problem_group_answer_types_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_on', models.DateTimeField(verbose_name='publish date')),
                ('is_full_markup', models.BooleanField(default=False, verbose_name='markup full')),
                ('is_public', models.BooleanField(default=False, verbose_name='public visibility')),
                ('content', models.TextField(verbose_name='editorial content')),
                ('authors', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='authors')),
                ('contest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solution', to='education.contest', verbose_name='contest')),
            ],
        ),
    ]
