# Generated by Django 4.0.2 on 2022-06-19 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_contestsolution'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('newbie', 'Newbie'), ('amateur', 'Amateur'), ('expert', 'Expert'), ('cmaster', 'Candidate Master'), ('master', 'Master'), ('gmaster', 'Grandmaster')], default='newbie', max_length=10, verbose_name='level')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='education.problemgroup', verbose_name='group')),
            ],
        ),
        migrations.AddField(
            model_name='problem',
            name='category',
            field=models.ManyToManyField(through='education.ProblemType', to='education.ProblemGroup', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='types',
            field=models.ManyToManyField(blank=True, help_text='The group of problem, shown under Category in the problem list.', related_name='problem1', to='education.ProblemGroup', verbose_name='group'),
        ),
        migrations.AddField(
            model_name='problemtype',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_types', to='education.problem', verbose_name='problem'),
        ),
        migrations.AlterUniqueTogether(
            name='problemtype',
            unique_together={('problem', 'group')},
        ),
    ]
