# Generated by Django 4.0.2 on 2022-06-19 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_problemtype_problem_category_alter_problem_types_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='types',
        ),
    ]
