# Generated by Django 4.0.2 on 2022-06-20 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('education', '0005_remove_problem_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_contest',
            field=models.BooleanField(default=True, verbose_name='is contest'),
        ),
        migrations.AddField(
            model_name='submission',
            name='problem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='education.problem', verbose_name='problem'),
        ),
        migrations.AddField(
            model_name='submission',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='profile'),
        ),
        migrations.AddField(
            model_name='submissionproblem',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='education.problem', verbose_name='problem'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='contest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='education.contest', verbose_name='contest'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='education.contestparticipation', verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='submissionproblem',
            name='problem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='education.contestproblem', verbose_name='contest problem'),
        ),
    ]
