# Generated by Django 4.0.2 on 2022-06-24 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_submission_is_contest_submission_problem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='difficult',
            field=models.CharField(choices=[('newbie', 'Newbie'), ('amateur', 'Amateur'), ('expert', 'Expert'), ('cmaster', 'Candidate Master'), ('master', 'Master'), ('gmaster', 'Grandmaster'), ('target', 'Target')], default='newbie', max_length=10, verbose_name='Difficult of problem'),
        ),
        migrations.AlterField(
            model_name='problemtype',
            name='level',
            field=models.CharField(choices=[('newbie', 'Newbie'), ('amateur', 'Amateur'), ('expert', 'Expert'), ('cmaster', 'Candidate Master'), ('master', 'Master'), ('gmaster', 'Grandmaster'), ('target', 'Target')], default='newbie', max_length=10, verbose_name='level'),
        ),
    ]
