# Generated by Django 4.0.2 on 2022-03-19 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of this post', max_length=255, verbose_name='title')),
                ('description', models.TextField(help_text='Content of this post', verbose_name='description')),
                ('publish', models.DateTimeField(auto_now_add=True, verbose_name='publish on time')),
                ('visible', models.BooleanField(default=False, verbose_name='visible')),
                ('author', models.ForeignKey(help_text='Creator of this post', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
            options={
                'permissions': (('edit_all_post', 'Edit all post'), ('change_blogpost', 'Change blogpost')),
            },
        ),
    ]
