# Generated by Django 4.0.2 on 2022-02-28 04:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('socical', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='date',
        ),
        migrations.AddField(
            model_name='blog',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='publish on time'),
        ),
        migrations.AddField(
            model_name='blog',
            name='visible',
            field=models.BooleanField(default=False, verbose_name='visible'),
        ),
    ]
